# Site settings
author: Isabella G Henriques
title: Sports to code
header-img: img/home-bg.png
email: isabellagh88@gmail.com
copyright_name: Isabella G Henriques
description: > # this means to ignore newlines until "baseurl:"
  Running for change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  isabellagh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
